import './style.css';
import { projects } from './project';
import buildHeader from './header';
import { projectRender } from './projectrender';
import { collapse } from './collapsible';
import buildSidebar from './sidebar/sidebar';
import { buildNav, newItemNav } from './sidebar/nav';
import { navprojects } from './sidebar/projects';
import projectForm from './projectform';
import todoForm from './todoform';
import domevents from './domevents';
import { listener } from './listener';
import { init } from './init';

buildHeader();
buildSidebar();
buildNav();
newItemNav();
init();
projectRender(projects.projects[0]);
navprojects();
collapse();
projectForm();
todoForm();
domevents.newProject();
domevents.projectClick();
domevents.todayClick();
domevents.thisWeekClick();
domevents.newToDo();
domevents.toDoClick();
domevents.deleteToDoClick();
domevents.editProjectTitle();
domevents.deleteProjectClick();
domevents.editToDoTitle();
domevents.editToDoDueDate();
domevents.editToDoPriority();
domevents.editToDoDescription();
domevents.editToDoNotes();
listener();
